#!/bin/sh
export __GL_SYNC_TO_VBLANK=0
export __NV_PRIME_RENDER_OFFLOAD=1
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export __VK_LAYER_NV_optimus=NVIDIA_only
export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json
export LIBVA_DRIVER_NAME=nvidia
export NVD_BACKEND=direct
export DXVK_ENABLE_NVAPI=1
export PROTON_HIDE_NVIDIA_GPU=0
export PROTON_ENABLE_NVAPI=1
export PROTON_ENABLE_NGX_UPDATER=1
export PROTON_FORCE_NVAPI=1
export MOZ_DISABLE_RDD_SANDBOX=1
exec "$@"
