#!/bin/sh

exec xinput list |                                   \
grep -Eio '(touchpad|glidepoint)\s*id=[0-9]{1,2}' |  \
grep -Eo '[0-9]{1,2}' |                              \
xargs -I'{}' sh -c "                                 \
  xinput disable {};                                 \
  echo 'Touchpad #'{}' disabled.';                   \
"
